### ISSUE TITLE
Check departmental filtering UI, not loading at 1st landing

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/faculty-search#118]
- [x] Department list not loading
- [x] Setting defaults (random sample from API) not loading

**Comment by JasonLo** [comment]
I found a bug after the change:

Problem: Author's articles is not fully rendered

How to reproduce:

1. Search "corn and fungicide"
2. Click "Damon Smith"
3. He should have much more publication than the UI rendered (The API Endpoint `get_author_by_id` did return all his publications)

![Image](https://github.com/UW-Madison-DSI/faculty-search/assets/1927986/6d613456-31bf-419e-afc9-5a485403df96)

* Both Firefox and Chrome has this problem

**Comment by amegahed** [comment]
This is caused by the duplicate ids in the list of articles.   If you'd like, I can work around that problem or we could fix the issue with the ids not being unique - Do you have a preference?

**Comment by amegahed** [comment]
Could you return the article ids as strings rather than integers?    If I parse the ids as integers, they get truncated which is causing the problem.     If this is a hassle, then I can work around the issue, but it seems like given the length of the ids, they should probably be treated as strings.

**Comment by amegahed** [comment]
Stripped problematic article ids.
