### ISSUE TITLE
A/B test?

### ISSUE THREAD

**Issue by JasonLo** [UW-Madison-DSI/faculty-search#84]
Goal: Refine system hyper-parameters using user feedback

- [x] Implement upvote and downvote buttons to collect target metrics.
- [x] Establish a database to store inputs, responses, and metrics.
- [x] #113 
- [x] Create an evaluation and reporting pipeline.

Let's talk first before doing anything.

**Comment by JasonLo** [comment]
What to store:

- Original query
- Which function the user is using
- Which search result's item the user is down-voting / up-voting
- Version's hyper-parameter or no.

- [ ] SQLite
- [ ] Cron job to sync to somewhere? 
- [ ] Manual report / auto... 
- [ ] Compare performance

**Comment by amegahed** [comment]
Added voting / recording of query parameters.   You can view the current voting results at:
https://dev.discover.datascience.wisc.edu/api/votes
